/**
 * seed-skills.js — Generate SQL to bulk-load all skills from db.js
 *                   into the Supabase `skills` table.
 *
 * Usage:
 *   node scripts/seed-skills.js            # writes seed-skills.sql
 *
 * Then paste the output SQL into the Supabase SQL Editor and run it.
 *
 * Column mapping (db.js → skills table):
 *   id            → id
 *   name          → name
 *   cat           → cat
 *   desc          → description
 *   trigger       → trigger
 *   difficulty    → difficulty
 *   timeToMaster  → time_to_master
 *   d             → d
 *   i             → i
 *   f             → f
 *   icon          → icon
 *   tags[]        → tags  (comma-separated TEXT)
 *   source        → source
 *   md            → md_content
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ── Load SKILLS_DB from db.js ────────────────────────────────────────
// db.js declares browser globals (const CATEGORIES, const SKILLS_DB).
// We evaluate it in a minimal sandbox to extract the data.
const dbPath = resolve(__dirname, '../js/db.js');
const src = readFileSync(dbPath, 'utf-8');

// Execute db.js in an isolated function scope so `const` declarations
// don't collide with our own. We capture CATEGORIES & SKILLS_DB.
let CATEGORIES, SKILLS_DB;
const fn = new Function(`
  ${src}
  return { CATEGORIES, SKILLS_DB };
`);
const data = fn();
CATEGORIES = data.CATEGORIES;
SKILLS_DB  = data.SKILLS_DB;

console.log(`Loaded ${SKILLS_DB.length} skills from db.js`);

// ── SQL escaping ─────────────────────────────────────────────────────
/** Escape a string for use inside a PostgreSQL single-quoted literal. */
function esc(val) {
  if (val == null) return 'NULL';
  const s = String(val)
    .replace(/'/g, "''");       // double single-quotes
  return `'${s}'`;
}

function escInt(val, fallback = 7) {
  const n = Number(val);
  return Number.isFinite(n) ? n : fallback;
}

// ── Generate SQL ─────────────────────────────────────────────────────
const lines = [];

lines.push('-- Auto-generated by scripts/seed-skills.js');
lines.push(`-- ${SKILLS_DB.length} skills from js/db.js`);
lines.push(`-- Generated: ${new Date().toISOString()}`);
lines.push('--');
lines.push('-- Run this in the Supabase SQL Editor after creating the skills table.');
lines.push('-- Uses INSERT ... ON CONFLICT to safely re-run (upsert).');
lines.push('');
lines.push('BEGIN;');
lines.push('');

for (const s of SKILLS_DB) {
  const tags = Array.isArray(s.tags) ? s.tags.join(', ') : (s.tags || '');

  lines.push(`INSERT INTO public.skills (
  id, name, cat, description, trigger, difficulty, time_to_master,
  d, i, f, icon, tags, source, status, md_content, submitted_by
) VALUES (
  ${esc(s.id)},
  ${esc(s.name)},
  ${esc(s.cat)},
  ${esc(s.desc)},
  ${esc(s.trigger)},
  ${esc(s.difficulty || 'intermediate')},
  ${esc(s.timeToMaster || '')},
  ${escInt(s.d)},
  ${escInt(s.i)},
  ${escInt(s.f)},
  ${esc(s.icon || '◈')},
  ${esc(tags)},
  ${esc(s.source || 'official')},
  'approved',
  ${esc(s.md)},
  'SkillGalaxy'
)
ON CONFLICT (id) DO UPDATE SET
  name          = EXCLUDED.name,
  cat           = EXCLUDED.cat,
  description   = EXCLUDED.description,
  trigger       = EXCLUDED.trigger,
  difficulty    = EXCLUDED.difficulty,
  time_to_master= EXCLUDED.time_to_master,
  d             = EXCLUDED.d,
  i             = EXCLUDED.i,
  f             = EXCLUDED.f,
  icon          = EXCLUDED.icon,
  tags          = EXCLUDED.tags,
  source        = EXCLUDED.source,
  md_content    = EXCLUDED.md_content,
  updated_at    = NOW();
`);
}

lines.push('COMMIT;');
lines.push('');
lines.push(`-- Done: ${SKILLS_DB.length} skills upserted into public.skills`);

const sql = lines.join('\n');
const outPath = resolve(__dirname, '../seed-skills.sql');
writeFileSync(outPath, sql, 'utf-8');

console.log(`✅ Wrote ${outPath}`);
console.log(`   ${SKILLS_DB.length} INSERT statements (${(sql.length / 1024).toFixed(0)} KB)`);
console.log(`\nNext: Paste seed-skills.sql into the Supabase SQL Editor and run it.`);
